#!/bin/bash
set -euo pipefail

rm -rf docs
haxelib run dox \
  --toplevel-package holen \
  -i lib/docs.xml \
  -o docs \
  -ex "ResponseTypes|QueryString" \
  --title "holen" \
  -D source-path https://github.com/statianzo/holen/blob/master/src/
